name: Veracode SAST and SCA Scan - From source repo

on:
    repository_dispatch:
      types: [veracode-build]

jobs:
  register:
    uses: ./.github/workflows/veracode-check-run.yml
    with:
      check_run_name: ${{ github.workflow }}
      head_sha: ${{ github.event.client_payload.sha }}
      repositroy_owner: ${{ github.event.client_payload.repository.owner }}
      repositroy_name: ${{ github.event.client_payload.repository.name }}
      event_type: ${{ github.event.client_payload.event_type }}
      github_token: ${{ github.event.client_payload.token }}
      run_id: ${{ github.run_id }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Prepare the SAST scan artifact
        run: zip -r veracode.zip . -x .git/**\* test/**\* .github/**\* .gitignore .gitattributes

      - uses: actions/upload-artifact@v3
        with:
          name: veracode-artifact
          path: veracode.zip

  veracode_policy_scan:
    needs: build
    runs-on: ubuntu-latest
    name: Veracode Static Code Analysis
    steps:
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory

      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV

      - name: Veracode Upload And Scan
        uses: veracode/uploadandscan-action@main
        with:
          appname: 'Veracode GitHub App'
          createprofile: true
          version: '${{ github.run_id }}'
          veracode_policy_name: 'Veracode Recommended High + SCA Random policy name'
          filepath: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          scanpollinginterval: 30
          scantimeout: 15
